name: Publish to NPM

on:
  push:
    tags:
      - '*'

permissions:
  contents: read
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '24.x'
          registry-url: 'https://registry.npmjs.org'
          package-manager-cache: false

      - name: Install dependencies and build
        run: npm install && npm run build

      - name: Publish package on npm
        run: npm publish --access public
